name: Publish releases

on:
  release:
    types: [published]

jobs:
  build-and-publish-pypi:
    name: Builds and publishes releases to PyPI
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"
      - name: Install build
        run: >-
          pip install build tomli tomli-w
      - name: Set Python project version from tag
        shell: python
        run: |-
          import tomli
          import tomli_w

          with open("pyproject.toml", "rb") as f:
            pyproject = tomli.load(f)

          pyproject["project"]["version"] = "${{ steps.vars.outputs.tag }}"

          with open("pyproject.toml", "wb") as f:
            tomli_w.dump(pyproject, f)
      - name: Build
        run: >-
          python3 -m build
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  build-and-push-container-image:
    name: Builds and pushes the Music Assistant Server container to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build-and-publish-pypi
    steps:
      - name: Sleep for 60 seconds (to prevent race condition with the pypi upload)
        run: sleep 60s
        shell: bash
      - uses: actions/checkout@v4
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Version number for tags
        id: tags
        shell: bash
        run: |-
          patch=${GITHUB_REF#refs/*/}
          echo "patch=${patch}" >> $GITHUB_OUTPUT
          echo "minor=${patch%.*}" >> $GITHUB_OUTPUT
          echo "major=${patch%.*.*}" >> $GITHUB_OUTPUT
          if [[ $patch =~ "b" ]]; then
            echo "channel=beta" >> $GITHUB_OUTPUT
          else
            echo "channel=stable" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/server

      - name: Build and Push images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |-
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.patch }},
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.minor }},
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.major }},
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.channel }},
            ghcr.io/${{ github.repository_owner }}/server:latest
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "MASS_VERSION=${{ needs.build-and-publish-pypi.outputs.version }}"

  release-notes-update:
    name: Updates the release notes and changelog
    needs: [ build-and-publish-pypi, build-and-push-container-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Update changelog and release notes including frontend notes
        uses: music-assistant/release-notes-merge-action@main
        with:
          github_token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
          release_tag: ${{ needs.build-and-publish-pypi.outputs.version }}

  addon-version-update:
    name: Updates the Addon repository with the new version
    needs: [ build-and-publish-pypi, build-and-push-container-image, release-notes-update ]
    runs-on: ubuntu-latest
    steps:
      - name: Push new version number to addon config
        uses: music-assistant/addon-update-action@main
        with:
          github_token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
          new_server_version: ${{ needs.build-and-publish-pypi.outputs.version }}
